fix: asset api
ca-risken/google pull request #118
Opened 2022-04-22 11:13 UTC by gassara-kys

AssetAPIのイテレーションコールの呼び出しが1件ずつになっているので、ある程度まとめてデータ取得するようにしてAPIコール回数を減らしたいと思います。（処理の高速化とRateLimitエラーのリスク軽減）
また、Findingデータの登録処理もこのタイミングでBatch APIをたたくようにしたいと思います

メモ: まとめてデータ取得するようになるとメモリ使用量が増える可能性があるのでリソース調整も要確認

2022-04-25 00:13 UTC, hnts requested changes

2022-04-25 00:13 UTC, hnts commented on src/asset/handler.go
> +func (s *sqsHandler) putFindingBatch(ctx context.Context, projectID uint32, params []*finding.FindingBatchForUpsert) error {
https://github.com/ca-risken/google/blob/master/src/scc/handler.go

このlimitずつputする処理はcommonなどに移して、↑や他のコードでも使えるようにした方がよさそうです

2022-04-25 00:13 UTC, hnts commented on src/asset/handler.go
> +func (s *sqsHandler) putResourceBatch(ctx context.Context, projectID uint32, params []*finding.ResourceBatchForUpsert) error {
https://github.com/ca-risken/google/blob/master/src/scc/handler.go

このlimitずつputする処理はcommonなどに移して、↑や他のコードでも使えるようにした方がよさそうです

2022-04-25 03:17 UTC, gassara-kys commented
https://github.com/ca-risken/core/pull/257
こちらで共通処理として切り出しました

2022-05-02 12:10 UTC, gassara-kys commented on src/asset/handler.go
> +func (s *sqsHandler) putFindingBatch(ctx context.Context, projectID uint32, params []*finding.FindingBatchForUpsert) error {
@hnts 共通ロジックに切り出し、sccとassetではそちらを使うようにしました

2022-05-02 12:10 UTC, gassara-kys commented on src/asset/handler.go
> +func (s *sqsHandler) putResourceBatch(ctx context.Context, projectID uint32, params []*finding.ResourceBatchForUpsert) error {
@hnts 共通ロジックに切り出し、sccとassetではそちらを使うようにしました

2022-05-06 07:11 UTC, hnts requested changes

2022-05-06 07:11 UTC, hnts commented on src/asset/handler.go
> +				appLogger.Warnf("Failed to Cloud Asset API, But retry call API after %d seconds..., retry=%d/%d, API Result=%+v, err=%+v",
小文字始まりでお願いします！

2022-05-06 07:33 UTC, gassara-kys commented on src/asset/handler.go
> +				appLogger.Warnf("Failed to Cloud Asset API, But retry call API after %d seconds..., retry=%d/%d, API Result=%+v, err=%+v",
改修範囲のサービスのログメッセージについては小文字はじまりにしました

2022-05-06 07:35 UTC, hnts commented
lgtm

2022-05-06 07:35 UTC, hnts approved these changes

2022-05-09 01:05 UTC, merged